INSERT INTO GENRES (GENRE_ID, GENRE_NAME) VALUES (1, 'COMEDY');
INSERT INTO GENRES (GENRE_ID, GENRE_NAME) VALUES (2, 'DRAMA');
INSERT INTO GENRES (GENRE_ID, GENRE_NAME) VALUES (3, 'CARTOON');
INSERT INTO GENRES (GENRE_ID, GENRE_NAME) VALUES (4, 'THRILLER');
INSERT INTO GENRES (GENRE_ID, GENRE_NAME) VALUES (5, 'DOCUMENTARY');
INSERT INTO GENRES (GENRE_ID, GENRE_NAME) VALUES (6, 'ACTION');

INSERT INTO MPA_RATINGS (MPA_ID, MPA_NAME) VALUES (1, 'G');
INSERT INTO MPA_RATINGS (MPA_ID, MPA_NAME) VALUES (2, 'PG');
INSERT INTO MPA_RATINGS (MPA_ID, MPA_NAME) VALUES (3, 'PG13');
INSERT INTO MPA_RATINGS (MPA_ID, MPA_NAME) VALUES (4, 'R');
INSERT INTO MPA_RATINGS (MPA_ID, MPA_NAME) VALUES (5, 'NC17');